# fly.toml app configuration file generated for barproject on 2024-03-11T15:02:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'barproject'
primary_region = 'lhr'

[build]
  image = 'jackmuir11/barproject:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51OleI4IOKQIgT1PnI41bvndvmKB7VGk6D2G0Gdjo1Ywh0CP436VAt3leDdWL9jvNKkqlnpeAgXBgf4twcMGSYOHC00TwWqdAJF"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

